### PR TITLE
Fix NoneType insert error

### LINKED ISSUE #34: Breakage @ master
```
$ sudo snap refresh --channel=edge juju-crashdump 
juju-crashdump (edge) 1.0.2+git35.05671e4 from Cory Johns (johnsca) refreshed

$ juju crashdump
Traceback (most recent call last):
  File "/snap/juju-crashdump/102/bin/juju-crashdump", line 11, in <module>
    load_entry_point('jujucrashdump==0.0.0', 'console_scripts', 'juju-crashdump')()
  File "/snap/juju-crashdump/102/lib/python2.7/site-packages/jujucrashdump/crashdump.py", line 393, in main
    opts.addons_file.insert(0, ADDONS_FILE_PATH)
AttributeError: 'NoneType' object has no attribute 'insert'
```

### PR DESCRIPTION
**Pull request by johnsca**
Fixes #34 which was caused by #33

### CODE REVIEW

**Comment by ktsakalozos** [comment]
LGTM +1
